package com.example.uke_3_4_oppgave

const val SHARED_PREFS_NAME = "shared_prefs_file"
const val SHARED_PREFS_ID_KEY = "SHARED_PREFS_ID_KEY"
const val SHARED_PREFS_USERNAME_KEY = "SHARED_PREFS_USERNAME_KEY"
const val SHARED_PREFS_FIRSTNAME_KEY = "SHARED_PREFS_FIRSTNAME_KEY"
